// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyncHms.Bus.EntityFramework.Sqlite.Infrastructure;

#nullable disable

namespace SyncHms.Bus.EntityFramework.Sqlite.Migrations
{
    [DbContext(typeof(SqliteBusContext))]
    [Migration("20240804212044_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Exchange", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Message", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("QueueName", "ExchangeName");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Queue", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeName")
                        .HasColumnType("TEXT");

                    b.HasKey("Name", "ExchangeName");

                    b.HasIndex("ExchangeName");

                    b.ToTable("Queues");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Message", b =>
                {
                    b.HasOne("SyncHms.Bus.EntityFramework.Models.Queue", "Queue")
                        .WithMany("Messages")
                        .HasForeignKey("QueueName", "ExchangeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Queue");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Queue", b =>
                {
                    b.HasOne("SyncHms.Bus.EntityFramework.Models.Exchange", "Exchange")
                        .WithMany("Queues")
                        .HasForeignKey("ExchangeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Exchange", b =>
                {
                    b.Navigation("Queues");
                });

            modelBuilder.Entity("SyncHms.Bus.EntityFramework.Models.Queue", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
