name: Docker Image Dev

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and Push the Docker image
      run: |
        docker build . -f src/SyncHms.Server/Dockerfile -t ivankopanyov/synchms:dev
        docker push ivankopanyov/synchms:dev
